import { validationResult } from 'express-validator';

/**
 * Middleware that handles validation errors generated by express-validator.
 * 
 * - If there are errors in the request, responds with status 400 and the array of errors.
 * - If there are no errors, proceeds to the next middleware.
 * 
 * @param {Request} req - Request object.
 * @param {Response} res - Response object.
 * @param {NextFunction} next - Function that passes control to the next middleware.
 * @returns {void|Response} Response with errors or call to `next()`.
 */
export const handleInputErrors = (req, res, next) => {
    const errors = validationResult(req);

    if (!errors.isEmpty()) {
        return res.status(400).json({ errors: errors.array() });
    }

    next();
};
